### ISSUE TITLE
Colour selectors/Background extension on images

### ISSUE THREAD

**Issue by lewiscowper** [kosamari/sweaterify#1]
Hi Mariko, first of all great project! I really found it amusing, and yet insightful to see the jumpers you created.

I come bearing a small feature request, which is the ability to change the colours of more bits of the jumper, so that images that don't have the correct shape or aspect ratio, can still be sweaterify-ed and look great.

As a for example, I uploaded this file:

![bear](https://cloud.githubusercontent.com/assets/593574/11782674/aa391952-a272-11e5-8ee3-0948b60f146b.png)

and the result was:

![sweaterify](https://cloud.githubusercontent.com/assets/593574/11782680/b634c008-a272-11e5-8075-9bdd0fe21439.png)

If I were able to change more of the colours, and add a "background" by taking "Color 2" and extending it outside the bounds of the original image, that'd be super cool!

**Comment by kosamari** [comment]
@lewiscowper just added "Fill background" button.
Thanks for suggestion :)

![sweaterify 6](https://cloud.githubusercontent.com/assets/4581495/11789445/6ded034a-a264-11e5-93f4-240b9a3f7910.png)
