### ISSUE TITLE
Probably wrong name

### ISSUE THREAD

**Issue by havenchyk** [kosamari/sweaterify#4]
Hi, it looks like sweaterify creates not sweater, but another dress item. Look at definition https://en.wikipedia.org/wiki/Sweater 

Maybe jumper or pullover will be better name, what do you think?

**Comment by jennschiffer** [comment]
i think sweater gets the point across

**Comment by jed** [comment]
i dunno, it's not, like, 100% the same tbh.

![image](https://cloud.githubusercontent.com/assets/4433/12240618/81d3590a-b85c-11e5-94ff-67736dc56c4f.png)

![image](https://cloud.githubusercontent.com/assets/4433/12240609/6de8f12a-b85c-11e5-8ac6-133fd4127ca5.png)

**Comment by havenchyk** [comment]
Okay, let's close issue, if everything is ok with the name.
