### ISSUE TITLE
Live demo

### ISSUE THREAD

**Issue by klihelp** [kosamari/sweaterify#5]
Can you have a link to a live demo?:)thanks

**Comment by kosamari** [comment]
what do you want to see ? the app it self is the live demo in a way... ?

**Comment by kosamari** [comment]
oh incase you haven't seen this link https://kosamari.github.io/sweaterify/

**Comment by klihelp** [comment]
Thanks for the link, couldn't see at the read-me. Happy xmas for your jumper.
